"""Index page for the eligibility clusters multi-page Streamlit app."""

from __future__ import annotations

import streamlit as st

from cluster_state import get_cluster_source_signature, get_clusters
from streamlit_utils import create_db_and_tables


def main() -> None:
    # st.set_page_config(page_title="Eligibility Clusters Explorer", layout="wide")
    # st.title("Eligibility Clusters Explorer")

    # st.write(
    #     "Welcome! This landing page provides context for the explorer. Use the "
    #     "sidebar to open **Cluster Explorer** where you can upload a CSV export "
    #     "and interact with the clusters."
    # )

    # clusters = get_clusters()
    # signature = get_cluster_source_signature()

    # if clusters:
    #     st.success(
    #         f"{len(clusters)} clusters currently loaded"
    #         + (f" from `{signature.split(':', 1)[0]}`." if signature else ".")
    #     )
    #     st.write(
    #         "- Head to **Cluster Explorer** to refine filters, inspect details, or "
    #         "download the current subset.\n"
    #         "- Upload a different CSV from that page to replace the dataset."
    #     )
    # else:
    #     st.info(
    #         "No clusters are loaded yet. Open **Cluster Explorer** from the sidebar "
    #         "to upload a CSV export and get started."
    #     )

    # st.subheader("Next steps")
    # st.write(
    #     "- Navigate to **Cluster Explorer** via the sidebar navigation.\n"
    #     "- Upload a clusters CSV generated by the visualizer.\n"
    #     "- Apply filters and review the detailed cluster breakdown."
    # )

    # Query parameters for navigation
    query_params = st.query_params
    criterion_id_from_url = query_params.get("criterion_id")
    requested_page = query_params.get("page")

    # Determine which page should be active by default
    trial_overview_default = False
    criterion_details_default = False

    if requested_page == "trial_overview":
        trial_overview_default = True
    elif requested_page == "criterion_details" or criterion_id_from_url:
        criterion_details_default = True
    else:
        trial_overview_default = True

    cluster_explorer = st.Page(
        "pages/cluster_explorer.py",
        title="Cluster Explorer",
        icon="🧩",
        default=False,
    )
    # Define pages
    trial_overview = st.Page(
        "pages/trial_overview.py",
        title="Trial Overview",
        icon="📊",
        default=False,
    )

    criterion_details = st.Page(
        "pages/criterion_details.py",
        title="Criterion Details",
        icon="📋",
        default=criterion_details_default,
    )

    # Navigation
    pg = st.navigation([cluster_explorer, trial_overview, criterion_details])
    pg.run()


if __name__ == "__main__":  # pragma: no cover - Streamlit entry point
    main()
